### ISSUE TITLE
Submodules

### ISSUE THREAD

**Issue by xlab** [deepakjois/harfbuzz-go#1]
Hi, I'd advise against using submodules, because that makes packages hardly go-getable:

```
$ go get github.com/deepakjois/harfbuzz-go
# cd /Users/xlab/Documents/dev/go/src/github.com/deepakjois/harfbuzz-go; git submodule update --init --recursive
fatal: no submodule mapping found in .gitmodules for path 'harfbuzz'
package github.com/deepakjois/harfbuzz-go: exit status 128
```

The best practice for cgogen bindings is to vendor all the required header files so the package won't depend upon any external code.

**Comment by deepakjois** [comment]
Thanks. I think I messed up the way I commit to git. This was not my intention at all.

**Comment by deepakjois** [comment]
Fixed now.
